language: node_js
node_js:
  - "node"
script:
  - cd ./functions
  - npm i
  - cd ..
  - "echo 'this is not a test'"
deploy:
  provider: firebase
  edge: true
  token:
    secure: "xQamjqGOTUsmdDalbK0eUqc1PDXGHxelkU9Ee4iqMzeZN7U9sOCr9OGNQOq+5WkNibmPETvnRX9sQrWScLHk07KC1h1R2Jx65VFOVwKbs4trfAFIJ+JbLi7g2bTXenyJpg8PYG44T6IHjd2fIiADEIY2f0IMoFsTxbXfz/x27uGJKVgBjzeXqpQcoNyy7T+tqr/RFL4yfenWCPuMkFxVavUPLa7EOiTh8rfre/L9JgvqbE/MA/WbvXWudHkRw8JBFXEoQkhnil4zafRT9TTbb5PFMKvYTvOnRJ5z1LogxgLMOMSET0vdv14Y56xZDQahH/Y7XfS/9EuYygL9Td6a143sVvdKT5OVx4kl1M3fPVAEWsuVQ83+JXN+UzargngfUSyTAPVIkCH3gSlyEdyyXLUIu5s3HAdktRXgFFOwfj0KnJvSW4xi9d0H3HAOwmGyN6FNz1vJDafXzqdtUnNOR59AdBzcfrfXwgxspl9H6BMTwczHc4jkpSAIPRJwqszgIUHQ/RPmZ8z8a+qhKGz8VcrkMPOpjyYsiT+7AiAjzWmCqlwLES0LsFVtv0l+pmnYw+ZOKZ7ueM2U0LGC4VXetfkLZchMFexCZtg8+f0xlzwr8hVnrCf92Jke6yZYJZtMDch4Im20O8ZC52HvUOimTrVXxvW83szCmNmgyfAt5WU="
