language: node_js
node_js:
  - "node"
cache:
  directories:
    - /front/node_modules
    - /functions/node_modules
install:
  - cd ./functions && npm i
  - cd ../front && npm i
  - cd ..
jobs:
  include:
  - stage: test
    script:
    - echo "test one"
    script:
    - echo "test two"
  - stage: build
    script:
    - echo "maaster brunch!!1"
    if: branch = master
