language: node_js
node_js:
  - "node"
script:
  - cd ./functions
  - npm i
  - cd ..
  - "echo 'this is not a test'"
  - npm i firebase-tools -g
  - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
