language: node_js
node_js:
  - "node"
script:
  - "echo 'this is not a test'"
deploy:
  provider: firebase
  token:
    secure: "hjE/DBlukCuQpZTLxiDLwZhlp/JIS78A2hL3yNIeKQUI98czLst3YJgjKvCXBBotclmif5cZNGAyKE33n6Z3IWo8Vc6I/tOoUFkNsZzQb9peTOJtiG+3LDNc9UIoqnBOYYSAcUwHqJL7QlKDEXZyQEDNjt5jNDJBa/YUtehgPnBY4ggQL+cJoGhKFPyjxFHJ2FoUOO6rQpKoGnFZ/t9lFDNCdeRzPGhWFiLZy3AZBY63pC2rFnPTuxBCsEJ5ydIQ1p5ZkrcqnAlliZImuuiJtCIkhX4lCzFj/1f6YdC5VEUQjQbLVcDZhaEP6t//hlne1z8NPHZwPPu/vdOVQWyLTqf2TIcaXWUoVDJ2blRzSVzK46sTC7/kPfXCLfNNw4h9UdJI/mWIaFIWKK22NDxsrMmm3ARwqmM3L+Vc7i8dM6ktqmDQS10RkZY/3M6IUp9wnG3jOfKK3lP64qYnO7a9ev6z666g6jXvhM4wMeBnAU1ZT6SbwXEMj/C0Pb317tKR5QBtVrkSuiBlQrHJyulJHIimaX7M261FYIgYP2kbqwDBvqYUGCn2Er5gmKqBQW1WWcCtw1CrPDuS8t/dRdVkFRR1ao9t0wzq9e3TrXqg8XPjbRwjvcuo/E/XH8vqk71VSWrkh1OoiKWmErf9emBVSyj5RN/h5Pna7yHD+nt9QKw="
